package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>学生主页</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url(../img/apic21738.jpg);\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("\tbackground-attachment: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left {\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground-color: #FFF;\r\n");
      out.write("\tbackground: rgba(230, 230, 230, 0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 78.5%;\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tmargin-left: 20.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj1 {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;;\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-family: youyuan;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj2 {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-family: youyuan;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj3 {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-family: youyuan;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj4 {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-family: youyuan;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj5 {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder: 0px solid #000;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-family: youyuan;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj1:hover {\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj2:hover {\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj3:hover {\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj4:hover {\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dj5:hover {\r\n");
      out.write("\tbackground-color: #A4A4FF;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-top: 750px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 110px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head00 {\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 130;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head01 {\r\n");
      out.write("\tfont-family: youyuan;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head02 {\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head03 {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head04 {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head05 {\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-right: 25px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" id=\"pageloader-css\" href=\"../css/pageloader.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"all\" />\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--加载 -->\r\n");
      out.write("\t<div id=\"bonfire-pageloader\">\r\n");
      out.write("\t\t<div class=\"bonfire-pageloader-icon\">\r\n");
      out.write("\t\t\t<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("\t\t\t\txmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"512px\"\r\n");
      out.write("\t\t\t\theight=\"512px\" viewBox=\"0 0 512 512\"\r\n");
      out.write("\t\t\t\tenable-background=\"new 0 0 512 512\" xml:space=\"preserve\"> <path\r\n");
      out.write("\t\t\t\tid=\"loading-12-icon\"\r\n");
      out.write("\t\t\t\td=\"M291,82.219c0,16.568-13.432,30-30,30s-30-13.432-30-30s13.432-30,30-30S291,65.65,291,82.219z\r\n");
      out.write("\t\t\t M261,404.781c-15.188,0-27.5,12.312-27.5,27.5s12.312,27.5,27.5,27.5s27.5-12.312,27.5-27.5S276.188,404.781,261,404.781z\r\n");
      out.write("\t\t\t M361.504,113.167c-4.142,7.173-13.314,9.631-20.487,5.489c-7.173-4.141-9.631-13.313-5.49-20.487\r\n");
      out.write("\t\t\tc4.142-7.173,13.314-9.631,20.488-5.489C363.188,96.821,365.645,105.994,361.504,113.167z M188.484,382.851\r\n");
      out.write("\t\t\tc-14.348-8.284-32.697-3.368-40.98,10.98c-8.285,14.349-3.367,32.696,10.98,40.981c14.35,8.283,32.697,3.367,40.98-10.981\r\n");
      out.write("\t\t\tC207.75,409.482,202.834,391.135,188.484,382.851z M421.33,184.888c-8.368,4.831-19.07,1.965-23.901-6.404\r\n");
      out.write("\t\t\tc-4.832-8.368-1.965-19.07,6.404-23.902c8.368-4.831,19.069-1.964,23.9,6.405C432.566,169.354,429.699,180.056,421.33,184.888z\r\n");
      out.write("\t\t\t M135.399,329.767c-8.285-14.35-26.633-19.266-40.982-10.982c-14.348,8.285-19.264,26.633-10.979,40.982\r\n");
      out.write("\t\t\tc8.284,14.348,26.632,19.264,40.981,10.98C138.767,362.462,143.683,344.114,135.399,329.767z M436.031,277.249\r\n");
      out.write("\t\t\tc-11.044,0-20-8.953-20-19.999c0-11.045,8.955-20.001,20.001-20.001c11.044,0,19.999,8.955,19.999,20.002\r\n");
      out.write("\t\t\tC456.031,268.295,447.078,277.249,436.031,277.249z M115.97,257.251c-0.001-16.57-13.433-30.001-30.001-30.002\r\n");
      out.write("\t\t\tc-16.568,0.001-29.999,13.432-30,30.002c0.001,16.566,13.433,29.998,30.001,30C102.538,287.249,115.969,273.817,115.97,257.251z\r\n");
      out.write("\t\t\t M401.333,364.248c-10.759-6.212-14.446-19.97-8.234-30.73c6.212-10.759,19.971-14.446,30.731-8.233\r\n");
      out.write("\t\t\tc10.759,6.211,14.445,19.971,8.232,30.73C425.852,366.774,412.094,370.46,401.333,364.248z M135.398,184.736\r\n");
      out.write("\t\t\tc8.285-14.352,3.368-32.698-10.98-40.983c-14.349-8.283-32.695-3.367-40.981,10.982c-8.282,14.348-3.366,32.696,10.981,40.981\r\n");
      out.write("\t\t\tC108.768,204,127.115,199.082,135.398,184.736z M326.869,421.328c-6.902-11.953-2.807-27.242,9.148-34.145\r\n");
      out.write("\t\t\ts27.243-2.806,34.146,9.149c6.902,11.954,2.806,27.243-9.15,34.145C349.059,437.381,333.771,433.284,326.869,421.328z\r\n");
      out.write("\t\t\t M188.482,131.649c14.352-8.286,19.266-26.633,10.982-40.982c-8.285-14.348-26.631-19.264-40.982-10.98\r\n");
      out.write("\t\t\tc-14.346,8.285-19.264,26.633-10.98,40.982C155.787,135.017,174.137,139.932,188.482,131.649z\"></svg>\r\n");
      out.write("\t\t\t<span\r\n");
      out.write("\t\t\t\tstyle=\"font-family: youyuan; font-size: 26px; font-weight: bold;\">奋斗中!</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t\t<div class=\"head00\">\r\n");
      out.write("\t\t\t\t\t<div class=\"head01\">教师综合评价系统</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"head02\">Teacher Evaluation System</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"head05\">\r\n");
      out.write("\t\t\t\t\t<div class=\"head03\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"logoff.jsp\" style=\"text-decoration: none;\">注销</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"head04\" id=\"time\">\r\n");
      out.write("\t\t\t\t\t\t<script>     \r\n");
      out.write("\tdocument.getElementById('time').innerHTML=new Date().toLocaleString();     \r\n");
      out.write("\tsetInterval(\"document.getElementById('time').innerHTML=new Date().toLocaleString();\",1000);\r\n");
      out.write("\tfunction getTime()\r\n");
      out.write("\t{\r\n");
      out.write("\t    var time = new Date();\r\n");
      out.write("\t    $(\"#time\").html(time.toLocaleString());\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t    setInterval(\"getTime()\",1000);\r\n");
      out.write("\t});  \r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"center\">\r\n");
      out.write("\t\t\t\t<div id=\"left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"editspass.jsp\" target=\"main\" style=\"text-decoration: none;\"><div\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dj3\">修改密码</div></a> <a href=\"student_evaluation.jsp\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"main\" style=\"text-decoration: none;\"><div id=\"dj4\">学生评价</div></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"right\">\r\n");
      out.write("\t\t\t\t\t<iframe name=\"main\" src=\"page2.jsp\" width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #FFF; background: rgba(230, 230, 230, 0.6); border-radius: 15px;\"\r\n");
      out.write("\t\t\t\t\t\tallowTransparency=\"true\"></iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-family: youyuan; font-size: 20px;\">重庆工程学院150010104班第五小组\r\n");
      out.write("\t\t\t\t\totaku team&nbsp;版权所有&nbsp;2016-2026&nbsp;ALL Right Reserved</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/pageloader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write(" $(document.body).css({\r\n");
      out.write("   \"overflow-x\":\"hidden\",\r\n");
      out.write("   \"overflow-y\":\"hidden\"\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("function resizenow() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar browserwidth = jQuery(window).width();\r\n");
      out.write("\tvar browserheight = jQuery(window).height();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery('.bonfire-pageloader-icon').css('right', ((browserwidth - jQuery(\".bonfire-pageloader-icon\").width())/2)).css('top', ((browserheight - jQuery(\".bonfire-pageloader-icon\").height())/2));\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tresizenow();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
